import React from "react";
import { Link } from "react-router-dom";
import {
  BarChartOutlined,
  LineChartOutlined,
  PieChartOutlined,
  DollarOutlined,
  CarOutlined,
  ThunderboltOutlined,
  CheckCircleOutlined
} from "@ant-design/icons";

export default function TransportReports({ isTab = false }) {
  const reports = [
    {
      title: "Trip Management & Execution Analytics",
      icon: <ThunderboltOutlined className="text-purple-600 dark:text-purple-400" />,
      desc: "Fleet dispatch velocity, route tracking, schedule delay SLA, driver throughput & financial performance",
      link: "/transport/reports/trip-execution",
      isFeatured: true,
      badge: "NEW"
    },
    {
      title: "Trip History & Tracking Report",
      icon: <BarChartOutlined className="text-indigo-500" />,
      desc: "Historical logs of all fleet trips, departure/destination timelines, and status logs",
      link: "/transport/reports/trip-history"
    },
    {
      title: "Transport Revenue Report",
      icon: <DollarOutlined className="text-emerald-500" />,
      desc: "Billing invoices and revenue generated by customer & internal transport orders",
      link: "/transport/reports/revenue"
    },
    {
      title: "Trip Profitability Analysis",
      icon: <LineChartOutlined className="text-blue-500" />,
      desc: "Cost vs revenue breakdown per trip, fuel expenses, and net profit margins",
      link: "/transport/reports/profitability"
    },
    {
      title: "Fuel Consumption Analytics",
      icon: <BarChartOutlined className="text-amber-500" />,
      desc: "Fuel logs, station spending, liter consumption, and mileage efficiency (km/L)",
      link: "/transport/reports/fuel"
    },
    {
      title: "Vehicle Utilization Report",
      icon: <PieChartOutlined className="text-purple-500" />,
      desc: "Active in-transit vs idle yard ratio, maintenance status, and vehicle throughput",
      link: "/transport/reports/utilization"
    },
    {
      title: "Driver Performance & Ratings",
      icon: <CheckCircleOutlined className="text-teal-500" />,
      desc: "Completed trip counts, distance driven, safety compliance, and delay incident tracking",
      link: "/transport/reports/driver-performance"
    },
    {
      title: "Trip Delays & SLA Issues",
      icon: <LineChartOutlined className="text-rose-500" />,
      desc: "Root-cause delay analysis, route bottleneck tracking, and schedule breach metrics",
      link: "/transport/reports/delays"
    },
  ];

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      {!isTab && (
        <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
          <div>
            <div className="flex items-center gap-2">
              <button onClick={() => window.history.back()} className="text-xs font-semibold text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 transition-colors"
              >
                ← Return to Transport Hub
              </button>
            </div>
            <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white mt-1">
              Transport Analytics & Intelligence Reports
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              Operational analytics, fleet KPIs, trip execution velocity, and financial profitability insights.
            </p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reports.map((report, idx) => (
          <Link
            key={idx}
            to={report.link}
            className={`group card hover:shadow-xl transition-all duration-300 bg-white dark:bg-slate-900 border rounded-2xl p-6 flex flex-col justify-between ${
              report.isFeatured
                ? "border-purple-200 dark:border-purple-900/60 ring-2 ring-purple-500/20 dark:ring-purple-500/40"
                : "border-slate-200 dark:border-slate-800 hover:border-indigo-300 dark:hover:border-indigo-800"
            }`}
          >
            <div>
              <div className="flex items-center justify-between mb-4">
                <div className="text-3xl p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/80 group-hover:scale-105 transition-transform flex items-center justify-center">
                  {report.icon}
                </div>
                {report.badge ? (
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-purple-100 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 uppercase">
                    {report.badge}
                  </span>
                ) : null}
              </div>
              <h3 className="font-bold text-base text-slate-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
                {report.title}
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 leading-relaxed">
                {report.desc}
              </p>
            </div>

            <div className="mt-5 pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs font-semibold text-indigo-600 dark:text-indigo-400">
              <span>View Report</span>
              <span className="group-hover:translate-x-1 transition-transform">→</span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
