/**
 * @fileoverview SalesReports component.
 * Modernized Analytics & Reports hub for Sales module listing all sales, revenue, and customer reports.
 */

import React from "react";
import { Link } from "react-router-dom";
import { 
  BarChart3, 
  TrendingUp, 
  Users, 
  FileText, 
  DollarSign, 
  ShoppingBag, 
  Percent, 
  Clock, 
  PieChart, 
  CheckCircle2, 
  ArrowUpRight,
  ChevronRight
} from "lucide-react";

export default function SalesReports() {
  const reportCategories = [
    {
      category: "Sales & Revenue Analysis",
      description: "Track revenue performance, product profitability, and periodical sales trends",
      reports: [
        {
          title: "Revenue by Customer",
          description: "Breakdown of total revenue generated by each customer account",
          path: "/sales/reports/revenue-by-customer",
          icon: Users,
          color: "text-blue-500 bg-blue-50 dark:bg-blue-950/40",
        },
        {
          title: "Revenue by Product",
          description: "Analysis of sales performance and revenue per product item",
          path: "/sales/reports/revenue-by-product",
          icon: ShoppingBag,
          color: "text-emerald-500 bg-emerald-50 dark:bg-emerald-950/40",
        },
        {
          title: "Monthly Sales Trend",
          description: "Month-over-month sales progression and growth metrics",
          path: "/sales/reports/monthly-sales-trend",
          icon: TrendingUp,
          color: "text-indigo-500 bg-indigo-50 dark:bg-indigo-950/40",
        },
        {
          title: "Sales Profitability",
          description: "Margin analysis comparing cost of sales to realized revenue",
          path: "/sales/reports/sales-profitability",
          icon: DollarSign,
          color: "text-amber-500 bg-amber-50 dark:bg-amber-950/40",
        },
        {
          title: "Sales Register",
          description: "Detailed chronological log of all posted sales transactions",
          path: "/sales/reports/sales-register",
          icon: FileText,
          color: "text-purple-500 bg-purple-50 dark:bg-purple-950/40",
        },
      ],
    },
    {
      category: "Orders & Fulfillment Tracking",
      description: "Monitor order status, delivery fulfillment, quotations, and conversions",
      reports: [
        {
          title: "Sales Order Status",
          description: "Real-time tracking of pending, processing, and completed sales orders",
          path: "/sales/reports/sales-order-status",
          icon: Clock,
          color: "text-sky-500 bg-sky-50 dark:bg-sky-950/40",
        },
        {
          title: "Delivery Register",
          description: "Log of completed goods deliveries and dispatch notes",
          path: "/sales/reports/delivery-register",
          icon: CheckCircle2,
          color: "text-teal-500 bg-teal-50 dark:bg-teal-950/40",
        },
        {
          title: "Quotation Summary & Conversion",
          description: "Track issued sales quotes and conversion rate to active orders",
          path: "/sales/reports/quotation-summary",
          icon: Percent,
          color: "text-rose-500 bg-rose-50 dark:bg-rose-950/40",
        },
      ],
    },
    {
      category: "Customer & Receivables",
      description: "Manage customer accounts, outstanding balances, and aging analysis",
      reports: [
        {
          title: "Customer Directory List",
          description: "Master list of registered customers, contact details, and credit limits",
          path: "/sales/reports/customer-list",
          icon: Users,
          color: "text-blue-600 bg-blue-50 dark:bg-blue-950/40",
        },
        {
          title: "Debtors Balance Summary",
          description: "Summary of outstanding customer ledger balances and receivables",
          path: "/sales/reports/debtors-balance",
          icon: PieChart,
          color: "text-orange-500 bg-orange-50 dark:bg-orange-950/40",
        },
        {
          title: "AR Aging Analysis",
          description: "Accounts receivable aging breakdown by 30, 60, 90+ days",
          path: "/sales/reports/ar-aging",
          icon: Clock,
          color: "text-red-500 bg-red-50 dark:bg-red-950/40",
        },
      ],
    },
  ];

  return (
    <div className="space-y-6 max-w-7xl mx-auto p-4 sm:p-6">
      {/* Header Banner */}
      <div className="card shadow-md">
        <div className="card-header bg-brand text-white rounded-t-lg p-5">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
              <h1 className="text-2xl font-bold flex items-center gap-2">
                <BarChart3 className="w-7 h-7" /> Sales Analytics & Reports Hub
              </h1>
              <p className="text-sm mt-1 opacity-90">
                Comprehensive reporting suite for revenue, customer activity, order fulfillment, and AR aging
              </p>
            </div>
            <Link to="/sales?section=Analytics%20%26%20Reports" className="btn btn-secondary text-xs">
              Return to Sales Menu
            </Link>
          </div>
        </div>
      </div>

      {/* KPI Overview Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div className="card p-4 border-l-4 border-brand bg-white dark:bg-slate-900 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Sales Reports</p>
            <h3 className="text-xl font-extrabold text-slate-900 dark:text-slate-100 mt-1">11 Active</h3>
          </div>
          <BarChart3 className="w-7 h-7 text-brand opacity-80" />
        </div>

        <div className="card p-4 border-l-4 border-emerald-500 bg-white dark:bg-slate-900 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Revenue Tracking</p>
            <h3 className="text-xl font-extrabold text-emerald-600 dark:text-emerald-400 mt-1">Live Sync</h3>
          </div>
          <TrendingUp className="w-7 h-7 text-emerald-500 opacity-80" />
        </div>

        <div className="card p-4 border-l-4 border-indigo-500 bg-white dark:bg-slate-900 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Order Analysis</p>
            <h3 className="text-xl font-extrabold text-indigo-600 dark:text-indigo-400 mt-1">Real-Time</h3>
          </div>
          <ShoppingBag className="w-7 h-7 text-indigo-500 opacity-80" />
        </div>

        <div className="card p-4 border-l-4 border-amber-500 bg-white dark:bg-slate-900 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Export Formats</p>
            <h3 className="text-xl font-extrabold text-amber-600 dark:text-amber-400 mt-1">Excel & PDF</h3>
          </div>
          <FileText className="w-7 h-7 text-amber-500 opacity-80" />
        </div>
      </div>

      {/* Report Categories & Cards */}
      <div className="space-y-8">
        {reportCategories.map((cat, idx) => (
          <div key={idx} className="space-y-3">
            <div className="border-b border-slate-200 dark:border-slate-800 pb-2">
              <h2 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-brand" />
                {cat.category}
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{cat.description}</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {cat.reports.map((r, rIdx) => {
                const IconComponent = r.icon;
                return (
                  <Link
                    key={rIdx}
                    to={r.path}
                    className="card p-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 hover:border-brand dark:hover:border-brand-500 shadow-sm hover:shadow-md transition-all group flex flex-col justify-between"
                  >
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <div className={`p-2.5 rounded-xl ${r.color}`}>
                          <IconComponent className="w-5 h-5" />
                        </div>
                        <ArrowUpRight className="w-4 h-4 text-slate-400 group-hover:text-brand group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-all" />
                      </div>
                      <h3 className="font-bold text-sm text-slate-900 dark:text-slate-100 group-hover:text-brand transition-colors">
                        {r.title}
                      </h3>
                      <p className="text-xs text-slate-500 dark:text-slate-400 line-clamp-2">
                        {r.description}
                      </p>
                    </div>
                    <div className="pt-3 mt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-[11px] font-semibold text-brand">
                      <span>Generate Report</span>
                      <ChevronRight className="w-3.5 h-3.5" />
                    </div>
                  </Link>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
